apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-service
  namespace: azure-chat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: session-service
  template:
    metadata:
      labels:
        app: session-service
    spec:
      containers:
      - name: session-service
        image: acrchatapp6fantofg.azurecr.io/session-service:latest
        ports:
        - containerPort: 8001
        env:
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: REDIS_HOST
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: REDIS_PASSWORD
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: REDIS_PORT
        - name: REDIS_SSL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: REDIS_SSL
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: session-service
  namespace: azure-chat-app
spec:
  selector:
    app: session-service
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
  type: ClusterIP
